const UserActionTypes={
    SET_CURRENT_TODO:'SET_CURRENT_TODO',
    SUBMIT_CURRENT_TODO:'SUBMIT_CURRENT_TODO',
    TOGGLE_CHECKED:'TOGGLE_CHECKED',
    TOGGLE_STATUS:'TOGGLE_STATUS',
    DELETE_TODO:'DELETE_TODO',
    COMPLETE_TODO:'COMPLETE_TODO',
    ACTION_CLEAR_TODO:'ACTION_CLEAR_TODO',
};

export default UserActionTypes;